### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.app.Activity.checkSelfPermission(java.lang.String)' on a null object reference

### ISSUE THREAD

**Issue by dmiedev** [flutter-package/images_picker#19]
Hi, I'm getting this error when I attempt to save a video to the gallery.
```
E/MethodChannel#chavesgu/images_picker(21452): Failed to handle method call
E/MethodChannel#chavesgu/images_picker(21452): java.lang.NullPointerException: Attempt to invoke virtual method 'int android.app.Activity.checkSelfPermission(java.lang.String)' on a null object reference
E/MethodChannel#chavesgu/images_picker(21452): 	at com.chavesgu.images_picker.ImagesPickerPlugin.hasPermission(ImagesPickerPlugin.java:324)
E/MethodChannel#chavesgu/images_picker(21452): 	at com.chavesgu.images_picker.ImagesPickerPlugin.onMethodCall(ImagesPickerPlugin.java:176)
E/MethodChannel#chavesgu/images_picker(21452): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#chavesgu/images_picker(21452): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#chavesgu/images_picker(21452): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/MethodChannel#chavesgu/images_picker(21452): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#chavesgu/images_picker(21452): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#chavesgu/images_picker(21452): 	at android.os.Looper.loop(Looper.java:174)
E/MethodChannel#chavesgu/images_picker(21452): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/MethodChannel#chavesgu/images_picker(21452): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#chavesgu/images_picker(21452): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/MethodChannel#chavesgu/images_picker(21452): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
I/flutter (21452): PlatformException(error, Attempt to invoke virtual method 'int android.app.Activity.checkSelfPermission(java.lang.String)' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'int android.app.Activity.checkSelfPermission(java.lang.String)' on a null object reference
I/flutter (21452): 	at com.chavesgu.images_picker.ImagesPickerPlugin.hasPermission(ImagesPickerPlugin.java:324)
I/flutter (21452): 	at com.chavesgu.images_picker.ImagesPickerPlugin.onMethodCall(ImagesPickerPlugin.java:176)
I/flutter (21452): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
I/flutter (21452): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
I/flutter (21452): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
I/flutter (21452): 	at android.os.MessageQueue.nativePollOnce(Native Method)
I/flutter (21452): 	at android.os.MessageQueue.next(MessageQueue.java:336)
I/flutter (21452): 	at android.os.Looper.loop(Looper.java:174)
I/flutter (21452): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
I/flutter (21452): 	at java.lang.refle
```
I use camera package to capture video.
```dart
    final video = await _cameraController.stopVideoRecording();
    final file = File(video.path);
    await ImagesPicker.saveVideoToAlbum(file);
    file.deleteSync();
```

**Comment by chavesgu** [comment]
please try git path below
```yaml
images_picker:
    git:
      url: https://github.com/flutter-package/images_picker.git
      ref: 451131c
```
