### ISSUE TITLE
crash after open camera on android 30,

### ISSUE THREAD

**Issue by ahmadvicky** [flutter-package/images_picker#69]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.0.1 21A559 darwin-x64, locale
    en-SG)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] Connected device (5 available)
Android 10, device Xiaomi 

after I call 

 List<Media> res = await ImagesPicker.openCamera(
      language: Language.English,
      pickType: PickType.image
    );

its look like going well, but after click done,

suddenly I check device already lost,
but I think it because not connecting with my laptop,

then I trying with 
flutter build apk --release 

the apps already force close,

I/Timeline(25777): Timeline: Activity_launch_request time:640251473
W/ActivityThread(25777): handleWindowVisibility: no activity for token android.os.BinderProxy@bdd3e64
W/com.csi.sellon(25777): Accessing hidden method Landroid/app/ActivityThread;->currentActivityThread()Landroid/app/ActivityThread; (greylist, reflection, allowed)
W/com.csi.sellon(25777): Accessing hidden method Landroid/app/ActivityThread;->getApplication()Landroid/app/Application; (greylist, reflection, allowed)
D/ForceDarkHelper(25777): updateByCheckExcludeList: pkg: com.csi.sellon activity: com.luck.picture.lib.PictureSelectorCameraEmptyActivity@d25e883
D/ForceDarkHelper(25777): updateByCheckExcludeList: pkg: com.csi.sellon activity: com.luck.picture.lib.PictureSelectorCameraEmptyActivity@d25e883
D/ForceDarkHelper(25777): updateByCheckExcludeList: pkg: com.csi.sellon activity: com.luck.picture.lib.PictureSelectorCameraEmptyActivity@d25e883
I/chatty  (25777): uid=10690(com.csi.sellon) identical 1 line
D/ForceDarkHelper(25777): updateByCheckExcludeList: pkg: com.csi.sellon activity: com.luck.picture.lib.PictureSelectorCameraEmptyActivity@d25e883
W/com.csi.sellon(25777): Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
W/com.csi.sellon(25777): Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
D/ForceDarkHelper(25777): updateByCheckExcludeList: pkg: com.csi.sellon activity: com.luck.picture.lib.PictureSelectorCameraEmptyActivity@d25e883
I/Timeline(25777): Timeline: Activity_launch_request time:640251760
W/com.csi.sellon(25777): Accessing hidden method Landroid/view/View;->getViewRootImpl()Landroid/view/ViewRootImpl; (greylist, reflection, allowed)
W/com.csi.sellon(25777): Accessing hidden field Landroid/view/View$AttachInfo;->mVisibleInsets:Landroid/graphics/Rect; (greylist, reflection, allowed)
W/com.csi.sellon(25777): Accessing hidden field Landroid/view/ViewRootImpl;->mAttachInfo:Landroid/view/View$AttachInfo; (greylist, reflection, allowed)
Lost connection to device.

**Comment by ahmadvicky** [comment]
and I try run again 

show like this 

W/Glide   (14572): There was 1 cause:
W/Glide   (14572): java.io.FileNotFoundException(open failed: ENOENT (No such file or directory))
W/Glide   (14572):  call GlideException#logRootCauses(String) for more detail
W/Glide   (14572):     Cause (1 of 1): class java.io.FileNotFoundException: open failed: ENOENT (No such file or directory)
I/Glide   (14572): Root cause (1 of 3)
I/Glide   (14572): java.io.FileNotFoundException: open failed: ENOENT (No such file or directory)
I/Glide   (14572): 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:149)
I/Glide   (14572): 	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:705)
I/Glide   (14572): 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1702)
I/Glide   (14572): 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1518)
I/Glide   (14572): 	at android.content.ContentResolver.openInputStream(ContentResolver.java:1202)
I/Glide   (14572): 	at com.bumptech.glide.load.data.StreamLocalUriFetcher.loadResourceFromUri(StreamLocalUriFetcher.java:74)
I/Glide   (14572): 	at com.bumptech.glide.load.data.StreamLocalUriFetcher.loadResource(StreamLocalUriFetcher.java:50)
I/Glide   (14572): 	at com.bumptech.glide.load.data.StreamLocalUriFetcher.loadResource(StreamLocalUriFetcher.java:13)
I/Glide   (14572): 	at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:44)
I/Glide   (14572): 	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
I/Glide   (14572): 	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.startNextOrFail(MultiModelLoader.java:164)
I/Glide   (14572): 	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onLoadFailed(MultiModelLoader.java:154)
I/Glide   (14572): 	at com.bumptech.glide.load.model.FileLoader$FileFetcher.loadData(FileLoader.java:76)
I/Glide   (14572): 	at com.bumptech.glide.load.model.stream.QMediaStoreUriLoader$QMediaStoreUriFetcher.loadData(QMediaStoreUriLoader.java:141)
I/Glide   (14572): 	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
I/Glide   (14572): 	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.startNextOrFail(MultiModelLoader.java:164)
I/Glide   (14572): 	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onDataReady(MultiModelLoader.java:147)
I/Glide   (14572): 	at com.bumptech.glide.load.data.mediastore.ThumbFetcher.loadData(ThumbFetcher.java:70)
I/Glide   (14572): 	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
I/Glide   (14572): 	at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(SourceGenerator.java:70)
I/Glide   (14572): 	at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:63)
I/Glide   (14572): 	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:310)
I/Glide   (14572): 	at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:279)
I/Glide   (14572): 	at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:234)
I/Glide   (14572): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
I/Glide   (14572): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
I/Glide   (14572): 	at java.lang.Thread.run(Thread.java:919)
I/Glide   (14572): 	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:393)
I/Glide   (14572): Root cause (2 of 3)
I/Glide   (14572): java.io.FileNotFoundException: open failed: ENOENT (No such file or directory)
I/Glide   (14572): 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:149)
I/Glide   (14572): 	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:705)
I/Glide   (14572): 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1702)
I/Glide   (14572): 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1518)
I/Glide   (14572): 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1435)
I/Glide   (14572): 	at com.bumptech.glide.load.data.FileDescriptorLocalUriFetcher.loadResource(FileDescriptorLocalUriFetcher.java:20)
I/Glide   (14572): 	at com.bumptech.glide.load.data.FileDescriptorLocalUriFetcher.loadResource(FileDescriptorLocalUriFetcher.java:12)
I/Glide   (14572): 	at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:44)
I/Glide   (14572): 	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
I/Glide   (14572): 	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.startNextOrFail(MultiModelLoader.java:164)
I/Glide   (14572): 	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onLoadFailed(MultiModelLoader.java:154)
I/Glide   (14572): 	at com.bumptech.glide.load.model.FileLoader$FileFetcher.loadData(FileLoader.java:76)
I/Glide   (14572): 	at com.bumptech.glide.load.model.stream.QMediaStoreUriLoader$QMediaStoreUriFetcher.loadData(QMediaStoreUriLoader.java:141)
I/Glide   (14572): 	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
I/Glide   (14572): 	at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(SourceGenerator.java:70)
I/Glide   (14572): 	at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:63)
I/Glide   (14572): 	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:310)
I/Glide   (14572): 	at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherFailed(DecodeJob.java:408)
I/Glide   (14572): 	at com.bumptech.glide.load.engine.SourceGenerator.onLoadFailedInternal(SourceGenerator.java:160)
I/Glide   (14572): 	at com.bumptech.glide.load.engine.SourceGenerator$1.onLoadFailed(SourceGenerator.java:83)
I/Glide   (14572): 	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.startNextOrFail(MultiModelLoader.java:167)
I/Glide   (14572): 	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onLoadFailed(MultiModelLoader.java:154)
I/Glide   (14572): 	at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:49)
I/Glide   (14572): 	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
I/Glide   (14572): 	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.startNextOrFail(MultiModelLoader.java:164)
I/Glide   (14572): 	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onLoadFailed(MultiModelLoader.java:154)
I/Glide   (14572): 	at com.bumptech.glide.load.model.FileLoader$FileFetcher.loadData(FileLoader.java:76)
I/Glide   (14572): 	at com.bumptech.glide.load.model.stream.QMediaStoreUriLoader$QMediaStoreUriFetcher.loadData(QMediaStoreUriLoader.java:141)
I/Glide   (14572): 	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
I/Glide   (14572): 	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.startNextOrFail(MultiModelLoader.java:164)
I/Glide   (14572): 	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onDataReady(MultiModelLoader.java:147)
I/Glide   (14572): 	at com.bumptech.glide.load.data.mediastore.ThumbFetcher.loadData(ThumbFetcher.java:70)
I/Glide   (14572): 	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
I/Glide   (14572): 	at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(SourceGenerator.java:70)
I/Glide   (14572): 	at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:63)
I/Glide   (14572): 	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:310)
I/Glide   (14572): 	at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:279)
I/Glide   (14572): 	at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:234)
I/Glide   (14572): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
I/Glide   (14572): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
I/Glide   (14572): 	at java.lang.Thread.run(Thread.java:919)
I/Glide   (14572): 	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:393)
I/Glide   (14572): Root cause (3 of 3)
I/Glide   (14572): java.io.FileNotFoundException: open failed: ENOENT (No such file or directory)
I/Glide   (14572): 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:149)
I/Glide   (14572): 	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:705)
I/Glide   (14572): 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1702)
I/Glide   (14572): 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1518)
I/Glide   (14572): 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1435)
I/Glide   (14572): 	at com.bumptech.glide.load.data.AssetFileDescriptorLocalUriFetcher.loadResource(AssetFileDescriptorLocalUriFetcher.java:20)
I/Glide   (14572): 	at com.bumptech.glide.load.data.AssetFileDescriptorLocalUriFetcher.loadResource(AssetFileDescriptorLocalUriFetcher.java:11)
I/Glide   (14572): 	at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:44)
I/Glide   (14572): 	at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(SourceGenerator.java:70)
I/Glide   (14572): 	at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:63)
I/Glide   (14572): 	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:310)
I/Glide   (14572): 	at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherFailed(DecodeJob.java:408)
I/Glide   (14572): 	at com.bumptech.glide.load.engine.SourceGenerator.onLoadFailedInternal(SourceGenerator.java:160)
I/Glide   (14572): 	at com.bumptech.glide.load.engine.SourceGenerator$1.onLoadFailed(SourceGenerator.java:83)
I/Glide   (14572): 	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.startNextOrFail(MultiModelLoader.java:167)
I/Glide   (14572): 	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onLoadFailed(MultiModelLoader.java:154)
I/Glide   (14572): 	at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:49)
I/Glide   (14572): 	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
I/Glide   (14572): 	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.startNextOrFail(MultiModelLoader.java:164)
I/Glide   (14572): 	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onLoadFailed(MultiModelLoader.java:154)
I/Glide   (14572): 	at com.bumptech.glide.load.model.FileLoader$FileFetcher.loadData(FileLoader.java:76)
I/Glide   (14572): 	at com.bumptech.glide.load.model.stream.QMediaStoreUriLoader$QMediaStoreUriFetcher.loadData(QMediaStoreUriLoader.java:141)
I/Glide   (14572): 	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
I/Glide   (14572): 	at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(SourceGenerator.java:70)
I/Glide   (14572): 	at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:63)
I/Glide   (14572): 	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:310)
I/Glide   (14572): 	at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherFailed(DecodeJob.java:408)
I/Glide   (14572): 	at com.bumptech.glide.load.engine.SourceGenerator.onLoadFailedInternal(SourceGenerator.java:160)
I/Glide   (14572): 	at com.bumptech.glide.load.engine.SourceGenerator$1.onLoadFailed(SourceGenerator.java:83)
I/Glide   (14572): 	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.startNextOrFail(MultiModelLoader.java:167)
I/Glide   (14572): 	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onLoadFailed(MultiModelLoader.java:154)
I/Glide   (14572): 	at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:49)
I/Glide   (14572): 	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
I/Glide   (14572): 	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.startNextOrFail(MultiModelLoader.java:164)
I/Glide   (14572): 	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onLoadFailed(MultiModelLoader.java:154)
I/Glide   (14572): 	at com.bumptech.glide.load.model.FileLoader$FileFetcher.loadData(FileLoader.java:76)
I/Glide   (14572): 	at com.bumptech.glide.load.model.stream.QMediaStoreUriLoader$QMediaStoreUriFetcher.loadData(QMediaStoreUriLoader.java:141)
I/Glide   (14572): 	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
I/Glide   (14572): 	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.startNextOrFail(MultiModelLoader.java:164)
I/Glide   (14572): 	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onDataReady(MultiModelLoader.java:147)
I/Glide   (14572): 	at com.bumptech.glide.load.data.mediastore.ThumbFetcher.loadData(ThumbFetcher.java:70)
I/Glide   (14572): 	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
I/Glide   (14572): 	at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(SourceGenerator.java:70)
I/Glide   (14572): 	at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:63)
I/Glide   (14572): 	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:310)
I/Glide   (14572): 	at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:279)
I/Glide   (14572): 	at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:234)
I/Glide   (14572): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
I/Glide   (14572): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
I/Glide   (14572): 	at java.lang.Thread.run(Thread.java:919)
I/Glide   (14572): 	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:393)

**Comment by Arjunraj-k** [comment]
Any update on this? im having the same issue.

**Comment by ahmadvicky** [comment]
>

**Comment by ahmadvicky** [comment]
you can update with new version
